### ISSUE TITLE
evaluation on my own dataset

### ISSUE THREAD

**Issue by Filippoghilo** [KTH-RPL/DeFlow#3]
Hi, thank you for your work and for making it publicly available!
I would be really interested into trying out your evaluation method on my own dataset, in particular producing flow results (I am not really interested in metric evaluation not having ground truth flow) using your checkpoints. I have LIDAR data (as binary files), poses and also ground segmentation which I saw should be the only things needed for evaluation, but I wanted to ask a couple of hints on what I should be really modifying to load my dataset. It would be really helpful for me!

**Comment by Kin-Zhang** [comment]
Hi,

If you want to evaluate your own dataset, you need have flow ground truth available, here are lines you may need read and format your dataset to h5 file:

https://github.com/KTH-RPL/DeFlow/blob/6f0321acbeb2de3c0839ba5f0b806387e54ab450/dataprocess/extract_av2.py#L192-L201

**Comment by 1eethink** [comment]
Hi,

How can I modify the code to have only two point clouds as input and get output result as a scene flow of those two point clouds? I don't need any ground masking or pose because I will assume that camera stays at the same location and there will be no background for the input point clouds.

I'm asking because even though I tried my best to change the code, there are too many arguments and parts I have to modify.

Thank you.
