### ISSUE TITLE
argoverse2 val experiment

### ISSUE THREAD

**Issue by wangyunlhr** [KTH-RPL/DeFlow#8]
Hi,
Thank you for sharing this great project! I’m currently trying to load the model(deflow_best.ckpt) and test it on the argoverse2 validation dataset, but I’m noticing that the results are slightly worse than expected. 
Dataprepocess: I didn't use the last line to transform.  [ego2sensor_pose]
![屏幕截图 2024-10-30 195021](https://github.com/user-attachments/assets/b79d0510-2aa6-4cb5-8cf4-314e10f9aa62)
 Could it be an issue with the data processing? I’m wondering about the coordinate transformation, as I’m not quite sure why it’s necessary.

![2](https://github.com/user-attachments/assets/43ebc859-ad83-4b7d-9305-ac30da929af8)

Thank you for your help!

**Comment by Kin-Zhang** [comment]
Yes, I think you should follow the dataprocess correctly and include that part, since it is trained on the sensor frame point cloud, the different is shown here: (if you comment the code will be the left one, and the correct is right one)
![](https://github.com/Kin-Zhang/linefit/blob/master/assets/docs/sensor_pos.png?raw=true)

**Comment by wangyunlhr** [comment]
Thank you for your help!
After transforming the points to the sensor coordinate system, should the flow labels also be transformed to the sensor coordinate system?

**Comment by Kin-Zhang** [comment]
No need, since this sensor coordinate is just higher the z a little bit, and the flow label is calculated the relative flow between p0 and p1, so it won't be affect is p0 p1 both transform to the same coor.

**Comment by wangyunlhr** [comment]
Got it, thank you very much!
